# docker-mongodb001

#****************************************
#Creating mongo db and mongoexpress container and attached network

version: '3.1'

services:

  mongodb001:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongodb001

###### run command in below for creating mongo db container
# docker compose -f .\docker-mongodb001-mongoexpress001.yaml up

###### run command in below for removing mongo db container
# docker compose -f .\docker-mongodb001-mongoexpress001.yaml down





